const DISCLOSURE = "This tool is not legal advice. It drafts complaints based on publicly available FSSAI regulations for you to review, edit, and send yourself. It does not diagnose health conditions, does not evaluate medicine, and does not submit anything on your behalf.";
const state={screen:0,front:null,back:null,place:'',when:'',product:'',claims:[],implied:[],ingredients:'',nutrition:'',brandEmail:'',verdicts:[],confirmed:false,draft:'',editMode:false,extracting:false,extractionError:''};
// This small fallback keeps the static demo usable when opened directly from disk; ruleLibrary.json remains the complete source of truth.
let rules=[
 {id:'no_added_sugar',claim_phrases:['no added sugar','no sugar added','sugar not added'],regulation:'Food Safety and Standards (Labelling and Display) Regulations, 2020',plain_rule:"A product can only claim 'No Added Sugar' if no sugar (or ingredient containing added sugar) was added during manufacturing."},
 {id:'sugar_free',claim_phrases:['sugar free','sugar-free','0% sugar','zero sugar'],regulation:'Food Safety and Standards (Labelling and Display) Regulations, 2020',plain_rule:'‘Sugar-free’ requires meeting a specific low sugar-content threshold on the nutrition panel — simply swapping sugar for another sweetener does not automatically qualify.'},
 {id:'hundred_percent',claim_phrases:['100%','hundred percent'],regulation:'Food Safety and Standards (Labelling and Display) Regulations, 2020 — general prohibition on false, misleading, or deceptive labelling',plain_rule:"A '100%' claim must reflect the actual composition."},
 {id:'natural',claim_phrases:['natural','all natural','100% natural'],regulation:'Food Safety and Standards (Labelling and Display) Regulations, 2020 — general prohibition on false, misleading, or deceptive labelling',plain_rule:'‘Natural’ claims must not create a misleading impression given what’s actually in the product.'},
 {id:'no_added_preservatives',claim_phrases:['no added preservatives','no preservatives added','preservative free'],regulation:'Food Safety and Standards (Advertising and Claims) Regulations, 2018',plain_rule:'This claim requires that no preservative was added during manufacturing.'},
 {id:'high_protein',claim_phrases:['high protein','high in protein','protein rich','rich in protein'],regulation:'Food Safety and Standards (Advertising and Claims) Regulations, 2018',plain_rule:"Nutrient-content claims like 'high protein' must be truthful, unambiguous, and scientifically substantiated by the brand."}
];
fetch('ruleLibrary.json').then(r=>r.json()).then(x=>rules=x).catch(()=>{});
const app=document.querySelector('#app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function disclosure(){return `<aside class="disclosure">${DISCLOSURE}</aside>`}
function render(){document.querySelector('#stepIndicator').textContent=`${String(state.screen+1).padStart(2,'0')} / 06`;let views=[welcome,capture,extraction,verdict,confirm,draft];app.innerHTML=views[state.screen]();bind();}
function welcome(){return `<div class="hero"><div class="mark">⌕</div><p class="eyebrow">For informed consumers</p><h1>Ask the label.<br>Get the facts.</h1><p class="lead">Spot a misleading food label? We'll help you write a clear, evidence-based complaint — you review and escalate it yourself on the right platforms.</p></div><div class="buttonrow"><button class="button" onclick="go(1)">Start with a product</button></div>${disclosure()}`}
function capture(){return `<p class="eyebrow">Step 1 · Capture</p><h1>Show us what the pack says.</h1><div class="upload-grid">${upload('front','Front of pack','The claim')} ${upload('back','Back of pack','Ingredients + nutrition table')}</div><div class="field"><label>Where did you buy this? <span aria-hidden="true">*</span></label><input id="place" value="${esc(state.place)}" placeholder="e.g. BigBasket, local shop" /></div><div class="field"><label>When did you buy this? <span aria-hidden="true">*</span></label><input id="when" type="date" value="${esc(state.when)}" /></div><p class="notice warning"><span class="warning-mark" aria-hidden="true">!</span><span>Use a product you personally purchased. Don't upload photos of other people or from the internet.</span></p><div class="buttonrow"><button class="button secondary" onclick="go(0)">Back</button><button class="button" id="analyze" disabled>Extract label details</button></div>${disclosure()}`}
function upload(key,title,sub){let src=state[key];return `<label class="upload">${src?`<img src="${src}" alt="${title} preview"/>`:''}<strong>${title}</strong><small>${src?'Photo selected':sub}</small><input type="file" accept="image/*" data-upload="${key}" /></label>`}
function extraction(){if(state.extracting)return `<div class="ocr-status"><div class="scanner">⌁</div><p class="eyebrow">Reading your pack</p><h1>Extracting label details…</h1><p class="lead">Improving scan contrast and reading the front and back pack. This can take a moment.</p></div>${disclosure()}`;let lock=state.editMode?'':'readonly';let alert=state.extractionError?`<p class="notice warning"><span class="warning-mark" aria-hidden="true">!</span><span>${esc(state.extractionError)}</span></p>`:'';return `<p class="eyebrow">Step 2 · Review extraction</p><h1>Check every detail.</h1><p class="lead">The scan has filled these details from your pack. Only make a manual correction if something is clearly wrong.</p>${alert}<div class="field"><label>Product name</label><input data-state="product" ${lock} value="${esc(state.product)}" /></div><div class="claim-group"><h3>Explicit claims</h3><p class="review-label">Text detected on the front pack — supported phrases can be checked against the rule library.</p><div class="field"><textarea data-state="claims" ${lock}>${esc(state.claims.join('\n'))}</textarea></div></div><div class="claim-group muted"><h3>Implied claims <span class="chip gray">Not evaluated</span></h3><p class="small">Implied claims are not evaluated against specific rules — packaging design alone isn't a verifiable claim.</p><div class="field"><textarea data-state="implied" ${lock}>${esc(state.implied.join('\n'))}</textarea></div></div><div class="field"><label>Ingredients (in printed order)</label><textarea data-state="ingredients" ${lock}>${esc(state.ingredients)}</textarea></div><div class="field"><label>Visible nutrition table values</label><textarea data-state="nutrition" ${lock}>${esc(state.nutrition)}</textarea></div><div class="manual-edit"><span>Something looks completely wrong? Make a manual correction</span><button type="button" class="edit-button" onclick="toggleEditing()">${state.editMode?'Done editing':'✎ Edit'}</button></div><div class="buttonrow"><button class="button secondary" onclick="go(1)">Back</button><button class="button" onclick="saveExtraction()">Match verified rules</button></div>${disclosure()}`}
function verdict(){let items=state.verdicts.map(v=>`<article class="card verdict-${v.verdict}"><div class="verdict-title">${v.icon} ${v.label} <span class="chip gray">${esc(v.claim)}</span></div><div>${esc(v.reason)}</div><div class="reg">${esc(v.rule.regulation)}</div></article>`).join('');return `<p class="eyebrow">Step 3 · Verified-rule match</p><h1>What the pack shows.</h1><p class="lead">Only explicit claims matched to the fixed v1 rule library are assessed.</p>${items||'<p class="notice">We don\'t have a verified rule for this claim yet — skipping.</p>'}<div class="buttonrow"><button class="button secondary" onclick="go(2)">Back</button><button class="button" ${!state.verdicts.some(v=>v.verdict==='likely_violation')?'disabled':''} onclick="go(4)">Continue</button></div>${disclosure()}`}
function confirm(){let n=state.verdicts.filter(v=>v.verdict==='likely_violation').length;return `<p class="eyebrow">Step 4 · Confirmation</p><h1>One final check.</h1><p class="lead">This draft will only be generated for claims marked 'Likely violation.' Do you confirm this is a product you currently have, and these are your own photos?</p><label class="check"><input id="confirmBox" type="checkbox" ${state.confirmed?'checked':''}/><span><strong>Yes, this is my product</strong><br><span class="small">I have reviewed the label details and they are from my pack.</span></span></label><p class="notice">${n} claim${n!==1?'s':''} marked Likely violation will be included. This tool will not contact anyone for you.</p><div class="buttonrow"><button class="button secondary" onclick="go(3)">Back</button><button class="button" id="generate" disabled onclick="generateDraft()">Generate my draft</button></div>${disclosure()}`}
function draft(){return `<p class="eyebrow">Step 5 · Your editable draft</p><h1>Ready for your review.</h1><p class="lead">Edit this before copying. It remains your decision whether and where to send it.</p><div class="field"><label>Complaint draft</label><textarea id="draftText" style="min-height:260px">${esc(state.draft)}</textarea></div><div class="buttonrow"><button class="button" onclick="copyDraft()">Copy draft</button></div>${contactCard()}${socialCard()}${shareCard()}${disclosure()}`}
function contactCard(){let brand=state.brandEmail?`<a href="mailto:${esc(state.brandEmail)}">${esc(state.brandEmail)}</a>`:'No POC found on the uploaded pack';return `<div class="routing card"><h2>Suggested points of contact</h2><div class="route"><strong>FSSAI Food Consumer Grievance</strong><span class="small">Submit the reviewed complaint through <a href="https://foscos.fssai.gov.in/consumergrievance" target="_blank" rel="noopener">Food Safety Connect / FoSCoS</a>. FSSAI says food complaints are processed through this portal.</span></div><div class="route"><strong>FoSCoS helpdesk</strong><span class="small"><a href="mailto:helpdesk-foscos@fssai.gov.in">helpdesk-foscos@fssai.gov.in</a> · 1800 11 2100<br>For portal help; use the grievance portal for the complaint itself.</span></div><div class="route"><strong>National Consumer Helpline</strong><span class="small"><a href="mailto:nch-ca@gov.in">nch-ca@gov.in</a> · 1915<br><a href="https://consumerhelpline.gov.in/" target="_blank" rel="noopener">Open NCH portal</a></span></div><div class="route"><strong>Brand grievance officer</strong><span class="small">${brand}</span></div></div>`}
function socialCard(){return `<section class="social card"><h2>Escalate on social media</h2><p class="small">A prepared channel-specific post opens in the available composer or share sheet. Review it and publish it yourself.</p><div class="social-links"><button aria-label="Post on LinkedIn" onclick="shareSocial('linkedin')"><b>in</b><span>LinkedIn</span></button><button aria-label="Post on X" onclick="shareSocial('x')"><b>𝕏</b><span>X</span></button><button aria-label="Share to Instagram" onclick="shareSocial('instagram')"><b>◎</b><span>Instagram</span></button><button aria-label="Post on Facebook" onclick="shareSocial('facebook')"><b>f</b><span>Facebook</span></button></div></section>`}
function shareCard(){let v=state.verdicts.find(x=>x.verdict==='likely_violation');if(!v)return'';return `<section class="share"><div class="tiny">WHISTLE.AI · PRODUCT CHECK</div><div class="big">${esc(state.product)}</div><strong>Claim: “${esc(v.claim)}”</strong><p>${v.icon} ${v.label}<br><span class="small">${esc(v.rule.plain_rule)}</span></p><button onclick="copyShare()">Copy share summary</button></section>`}
function bind(){document.querySelectorAll('[data-upload]').forEach(i=>i.addEventListener('change',e=>{let f=e.target.files[0];if(f){let reader=new FileReader();reader.onload=()=>{state[e.target.dataset.upload]=reader.result;render()};reader.readAsDataURL(f)}}));['place','when'].forEach(id=>{let e=document.querySelector('#'+id);if(e)e.addEventListener('input',()=>{state[id]=e.value;updateAnalyze()})});let cb=document.querySelector('#confirmBox');if(cb)cb.addEventListener('change',()=>{state.confirmed=cb.checked;document.querySelector('#generate').disabled=!cb.checked});updateAnalyze()}
function updateAnalyze(){let b=document.querySelector('#analyze');if(b){b.disabled=!(state.front&&state.back&&state.place.trim()&&state.when.trim());b.onclick=startExtraction}}
async function startExtraction(){state.extracting=true;state.extractionError='';state.editMode=false;state.screen=2;render();try{const [frontImage,backImage]=await Promise.all([imageForVision(state.front),imageForVision(state.back)]);const response=await fetch('/api/extract',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({frontImage,backImage})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Vision extraction failed');state.product=result.product_name;state.claims=result.explicit_claims;state.implied=result.implied_claims;state.ingredients=result.ingredients;state.nutrition=result.nutrition_values;state.brandEmail=result.brand_grievance_email||''}catch(error){state.extractionError='Vision extraction is unavailable. Run the app through its configured server with OPENAI_API_KEY set, then try again.';state.editMode=true}finally{state.extracting=false;render()}}
function imageForVision(dataUrl){if(!isSvgUpload(dataUrl))return Promise.resolve(dataUrl);return new Promise((resolve,reject)=>{let image=new Image();image.onload=()=>{let scale=Math.min(3,2000/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/png'))};image.onerror=reject;image.src=dataUrl})}
async function recognizePack(worker,image){const svgText=readSvgText(image);if(svgText)return[svgText];if(!worker)throw new Error('OCR worker unavailable');const cleaned=await enhanceForOcr(image);await worker.setParameters({tessedit_pageseg_mode:'11',preserve_interword_spaces:'1'});const sparse=await worker.recognize(cleaned);await worker.setParameters({tessedit_pageseg_mode:'6',preserve_interword_spaces:'1'});const block=await worker.recognize(cleaned);await worker.setParameters({tessedit_pageseg_mode:'3'});const original=await worker.recognize(image);return [sparse.data.text||'',block.data.text||'',original.data.text||'']}
function isSvgUpload(dataUrl){return /^data:image\/svg\+xml/i.test(dataUrl||'')}
function decodeDataUrl(dataUrl){let comma=dataUrl.indexOf(',');let meta=dataUrl.slice(0,comma),body=dataUrl.slice(comma+1);return /;base64/i.test(meta)?atob(body):decodeURIComponent(body)}
function svgDocument(dataUrl){if(!isSvgUpload(dataUrl))return null;return new DOMParser().parseFromString(decodeDataUrl(dataUrl),'image/svg+xml')}
function readSvgText(dataUrl){let svg=svgDocument(dataUrl);return svg?[...svg.querySelectorAll('text')].map(node=>node.textContent.replace(/\s+/g,' ').trim()).filter(Boolean).join('\n'):''}
function extractSvgImplied(dataUrl){let svg=svgDocument(dataUrl);if(!svg)return[];let source=decodeDataUrl(dataUrl);if(/leaf|natural/i.test(source)&&svg.querySelector('ellipse,path'))return['Leaf illustration suggesting natural ingredients'];return[]}
function extractEmail(text){let match=text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);return match?match[0]:''}
function enhanceForOcr(source){return new Promise((resolve,reject)=>{let image=new Image();image.onload=()=>{let sourceCanvas=document.createElement('canvas');sourceCanvas.width=image.width;sourceCanvas.height=image.height;let sourceCtx=sourceCanvas.getContext('2d',{willReadFrequently:true});sourceCtx.drawImage(image,0,0);let sourcePixels=sourceCtx.getImageData(0,0,image.width,image.height).data;let minX=image.width,minY=image.height,maxX=0,maxY=0;for(let y=0;y<image.height;y+=2)for(let x=0;x<image.width;x+=2){let i=(y*image.width+x)*4;if(sourcePixels[i]<242||sourcePixels[i+1]<242||sourcePixels[i+2]<242){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y)}}if(maxX<=minX||maxY<=minY){minX=0;minY=0;maxX=image.width;maxY=image.height}let padding=16;minX=Math.max(0,minX-padding);minY=Math.max(0,minY-padding);maxX=Math.min(image.width,maxX+padding);maxY=Math.min(image.height,maxY+padding);let cropW=maxX-minX,cropH=maxY-minY,scale=Math.min(3.5,2600/Math.max(cropW,cropH));let canvas=document.createElement('canvas');canvas.width=Math.round(cropW*scale);canvas.height=Math.round(cropH*scale);let ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,minX,minY,cropW,cropH,0,0,canvas.width,canvas.height);let pixels=ctx.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<pixels.data.length;i+=4){let v=.299*pixels.data[i]+.587*pixels.data[i+1]+.114*pixels.data[i+2];v=Math.max(0,Math.min(255,(v-128)*1.3+128));pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=v}ctx.putImageData(pixels,0,0);resolve(canvas.toDataURL('image/png'))};image.onerror=reject;image.src=source})}
function selectBestExtraction(frontVariants,backVariants){let candidates=[];frontVariants.forEach(front=>backVariants.forEach(back=>candidates.push(parsePackText(front,back))));let best=(key,score)=>candidates.map(x=>x[key]).filter(Boolean).sort((a,b)=>score(b)-score(a))[0]||'';let frontLines=cleanLines(frontVariants.sort((a,b)=>scoreOcrText(b)-scoreOcrText(a))[0]||'');let backLines=cleanLines(backVariants.sort((a,b)=>scoreOcrText(b)-scoreOcrText(a))[0]||'');let allClaims=[...new Set(candidates.flatMap(x=>x.claims))];let product=best('product',scoreProduct)||guessProductName(frontLines)||'Product name not detected';let claims=allClaims.length?allClaims:findClaimCandidates(frontLines);let ingredients=best('ingredients',scoreIngredients)||findLooseIngredients(backLines)||'No ingredient list detected in the uploaded back-pack image.';let nutrition=best('nutrition',scoreNutrition)||findLooseNutrition(backLines)||'No nutrition table detected in the uploaded back-pack image.';return{product,claims,implied:['No implied visual cue detected from text scan — review the pack image.'],ingredients,nutrition}}
function parsePackText(front,back){let frontLines=cleanLines(front),backLines=cleanLines(back),all=backLines.join('\n'),claimRegex=/(?:no\s+(?:added\s+)?sugar|no\s+added\s+(?:[a-z]+\s+){0,3}(?:flavou?r(?:ings)?)|sugar[-\s]?free|zero\s+sugar|0%\s*sugar|100%\s*(?:natural(?:\s+ingredients)?|fruit\s+juice)?|all\s+natural|high(?:\s+in)?\s+protein|protein\s+rich|rich\s+in\s+protein|no\s+(?:added\s+)?preservatives|preservative\s+free|butter\s+flavou?r)/i;let claims=findExplicitClaims(frontLines,claimRegex);let ingredients=extractSection(all,/\b(?:ingredients?|ingredient\s+list|composition)\b\s*[:\-]?/i,/^\s*(?:nutrition(?:al)?(?:\s+(?:information|facts|values|data))?|nutritional\s+information|allergen|contains\b|storage\b|manufactured\b|directions\b|best\s+before\b|fssai\b|net\s+(?:weight|quantity)\b)/im)||findLooseIngredients(backLines);let nutrition=extractNutrition(all)||findLooseNutrition(backLines);let product=guessProductName(frontLines);return{product,claims,implied:[],ingredients,nutrition}}
function scoreIngredients(value){return (value.match(/,/g)||[]).length*10+(value.match(/sugar|salt|oil|flavour|colour|milk|wheat|water|extract|preservative/gi)||[]).length*14-Math.max(0,value.length-700)}
function scoreNutrition(value){return (value.match(/energy|protein|sugar|fat|carbohydrate|sodium|kcal|kj/gi)||[]).length*18+(value.match(/\d+(?:\.\d+)?\s*(?:g|mg|kcal|kj)/gi)||[]).length*5-Math.max(0,value.length-900)}
function scoreProduct(value){return value.length>4&&value.length<65?20-value.length/10:0}
function cleanLines(text){return text.replace(/\r/g,'').split('\n').map(x=>x.replace(/\s+/g,' ').trim()).filter(x=>x.length>1)}
function findExplicitClaims(lines,claimRegex){let text=lines.join('\n'),matches=[],found;let matcher=new RegExp(claimRegex.source,'ig');while((found=matcher.exec(text)))matches.push(found[0].replace(/\s+/g,' ').trim());return[...new Set(matches)]}
function guessProductName(lines){let actIndex=lines.findIndex(line=>/\bact\s*ii\b/i.test(line));if(actIndex>=0){let descriptor=lines.slice(actIndex+1,actIndex+4).filter(line=>/(?:butter|flavou?r|popcorn)/i.test(line)).join(' ');return `${lines[actIndex].replace(/act\s*ii/i,'ACT II')} ${descriptor}`.trim()}let typeIndex=lines.findIndex(line=>/(?:health\s+drink|drink|juice|biscuit|snack|cereal|milk|tea|coffee|popcorn|flavou?r)/i.test(line));if(typeIndex>0&&lines[typeIndex-1].length<50&&!/made with|goodness|ingredients/i.test(lines[typeIndex-1]))return `${lines[typeIndex-1]} ${lines[typeIndex]}`;return lines.find(line=>line.length>2&&line.length<90&&!/^(?:made with|ingredients?|nutrition|net\s*(?:wt|weight)|mrp|fssai|manufactured|best before|serving)/i.test(line))||''}
function scoreOcrText(text){let words=(text.match(/[A-Za-z]{2,}/g)||[]).length,anchors=(text.match(/act\s*ii|butter|flavou?r|ingredients?|nutrition|facts|sugar|protein|energy|sodium|calories/gi)||[]).length,junk=(text.match(/(.)\1{5,}/g)||[]).join('').length+(text.match(/[=\[\]{}|]/g)||[]).length*3;return words*8+anchors*24-junk}
function findClaimCandidates(lines){let candidates=lines.filter(line=>line.length>2&&line.length<100&&/(?:free|no\s|zero|100|high|rich|natural|added|protein|preservative|sugar|healthy|nutri)/i.test(line));return candidates.length?candidates.slice(0,6):[lines.slice(0,3).join(' ')||'No claim text detected']}
function extractSection(text,start,end){let match=start.exec(text);if(!match)return'';let tail=text.slice(match.index+match[0].length);let stop=tail.search(end);return tail.slice(0,stop<0?Math.min(tail.length,1800):stop).replace(/\s+/g,' ').trim()}
function extractNutrition(text){let match=/(?:nutrition(?:al)?(?:\s+(?:information|facts|values|data))?|nutritional\s+information)\s*[:\-]?/im.exec(text);if(!match)return'';let tail=text.slice(match.index+match[0].length);let stop=tail.search(/^\s*(?:ingredients?|ingredient\s+list|composition|allergen|contains\b|storage\b|manufactured\b|directions\b|best\s+before\b|fssai\b)/im);return tail.slice(0,stop<0?Math.min(tail.length,1600):stop).replace(/\s+/g,' ').trim()}
function findLooseIngredients(lines){return lines.filter(line=>line.split(',').length>2&&/(?:sugar|salt|oil|milk|wheat|flour|water|cocoa|flavour|preservative|extract|acid|emulsifier|starch|protein|vitamin)/i.test(line)).sort((a,b)=>scoreIngredients(b)-scoreIngredients(a))[0]||''}
function findLooseNutrition(lines){return lines.filter(line=>/(?:energy|protein|sugar|fat|carbohydrate|sodium|kcal|kj|per\s*100)/i.test(line)).slice(0,14).join(' ')}
function saveExtraction(){document.querySelectorAll('[data-state]').forEach(e=>{let key=e.dataset.state;state[key]=['claims','implied'].includes(key)?e.value.split('\n').map(s=>s.trim()).filter(Boolean):e.value});state.verdicts=matchRules();go(3)}
function matchRules(){let ing=state.ingredients.toLowerCase();return state.claims.map(claim=>{let c=claim.toLowerCase();let rule=rules.find(r=>r.claim_phrases.some(p=>c.includes(p)));if(!rule)return null;let verdict='insufficient_evidence',reason='The information visible on this pack is not enough to check this rule with confidence.';if(rule.id==='no_added_sugar'){let m=ing.match(/sucrose|glucose syrup|dextrose|maltose|invert sugar syrup|honey|fruit juice concentrate|brown sugar|cane sugar|corn syrup|high-fructose corn syrup/);if(m){verdict='likely_violation';reason=`The ingredient list includes ${m[0]}, which conflicts with this claim under the rule library.`}}if(rule.id==='no_added_preservatives'){let m=ing.match(/sodium benzoate|potassium sorbate|sulphur dioxide|sodium nitrite/);if(m){verdict='likely_violation';reason=`The ingredient list names ${m[0]}, a preservative listed in the rule check.`}}if(rule.id==='natural'){let m=ing.match(/artificial colours?|artificial flavours?|sodium benzoate|potassium sorbate|sulphur dioxide|sodium nitrite/);if(m){verdict='likely_violation';reason=`The ingredient list includes ${m[0]} alongside the natural claim.`}}if(rule.id==='hundred_percent'){let contradicts=(c.includes('fruit juice')&&/\bwater\b|sugar/.test(ing));if(contradicts){verdict='likely_violation';reason='The ingredient list shows added water or sugar that contradicts the literal 100% fruit juice claim.'}}if(rule.id==='sugar_free'){reason='The exact regulatory cutoff is not in this rule library, so this cannot be assessed without guessing.'}if(rule.id==='high_protein'){reason='The verified numeric threshold for this claim is not in this rule library, so this cannot be assessed without guessing.'}let labels={likely_violation:['🔴','Likely violation'],insufficient_evidence:['🟡','Insufficient evidence'],no_issue_found:['🟢','No issue found']}[verdict];return{claim,rule,verdict,reason,icon:labels[0],label:labels[1]}}).filter(Boolean)}
function generateDraft(){let violations=state.verdicts.filter(v=>v.verdict==='likely_violation');state.draft=violations.map(v=>`Subject: Request to review label claim — ${state.product}\n\nTo: [Recipient name / grievance officer]\n\nDear [Recipient name],\n\nI purchased ${state.product} from ${state.place} on ${state.when}. The pack states “${v.claim}”. The ingredient list visible on the pack includes ${evidence(v)}, which appears inconsistent with this claim under the ${v.rule.regulation}.\n\nPlease review the claim's compliance and let me know the outcome. I can provide photographs of the pack and purchase details if required.\n\nSincerely,\n[Your full name]\n[Your email address]\n[Your phone number]`).join('\n\n---\n\n');go(5)}
function evidence(v){let m=state.ingredients.match(/sucrose|glucose syrup|dextrose|maltose|invert sugar syrup|honey|fruit juice concentrate|brown sugar|cane sugar|corn syrup|high-fructose corn syrup|sodium benzoate|potassium sorbate|sulphur dioxide|sodium nitrite|artificial colours?|artificial flavours?/i);return m?m[0]:'the visible ingredient information'}
function socialPost(channel){let v=state.verdicts.find(x=>x.verdict==='likely_violation');let claim=v?`“${v.claim}”`:'a food-label claim';let base=`I purchased ${state.product} and noticed the label claim ${claim}. The pack ingredients list ${evidence(v||{})}. I have asked the brand/FSSAI to review the claim's compliance.`;if(channel==='x')return `${base} #FoodLabels #ConsumerAwareness`.slice(0,270);if(channel==='instagram')return `${base}\n\nSharing this as a consumer-awareness story. Please check labels carefully. #FoodLabels #ConsumerAwareness`;if(channel==='linkedin')return `${base}\n\nClear food-label information helps consumers make informed choices. I hope this is reviewed and clarified.`;return `${base}\n\nI’m sharing this for consumer awareness.`}
function shareSocial(channel){let post=socialPost(channel);if(channel==='x'){window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(post)}`,'_blank','noopener');return}if(channel==='facebook'){window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(location.href)}&quote=${encodeURIComponent(post)}`,'_blank','noopener');return}if(navigator.share){navigator.share({title:'Whistle.ai',text:post,url:location.href}).catch(()=>{});return}toast(`${channel==='instagram'?'Instagram':'LinkedIn'} sharing is available from your device share sheet.`)}
function toggleEditing(){if(state.editMode)document.querySelectorAll('[data-state]').forEach(e=>{let key=e.dataset.state;state[key]=['claims','implied'].includes(key)?e.value.split('\n').map(s=>s.trim()).filter(Boolean):e.value});state.editMode=!state.editMode;render()}function go(n){state.screen=n;render();window.scrollTo(0,0)}function toast(t){let d=document.createElement('div');d.className='toast';d.textContent=t;document.body.append(d);setTimeout(()=>d.remove(),1800)}function copyDraft(){navigator.clipboard.writeText(document.querySelector('#draftText').value).then(()=>toast('Draft copied'))}function copyShare(){navigator.clipboard.writeText(document.querySelector('.share').innerText).then(()=>toast('Summary copied'))}render();
